### ISSUE TITLE
.NET 4.0 Usage

### ISSUE THREAD

**Issue by rschiefer** [davidwhitney/ReallySimpleFeatureToggle#6]
We are using RSFT on many of our MVC 4 web applications in VS 2013.  We would also like to use it for our CodedUI feature tests which are in VS2010 until we update beyond TFS 2010.  The problem is we can't use RSFT.Web/Web.MVC with this project because they are targeting the 4.5 framework.  

I did a quick test by pulling down the RSFT source and downgraded to 4.0.  The only error I saw was on a usage of the DataContractJsonSerializerSettings type which apparently does not exist in 4.0.  Is this a necessary feature or could it be replaced with a 4.0 alternative?

Are there other reasons not to target 4.0 and enable more compatibility?

Thanks!

**Comment by davidwhitney** [comment]
I'll take a look to see if there's any other implementations of the settings serialisation that I can cook up - seems like a reasonable request :+1:

**Comment by davidwhitney** [comment]
Right, the current tip of master has unfinished support for .NET4 now - just needs a final implementation for cookie storage settings - I literally just switched out for the XML serializer in NET40 for that version of the framework - seems kind of icky - going to sleep on what is probably the best solution here.

Any thoughts? Feel free to clone the repo and build it - should produce packages with .NET4 binaries.

**Comment by davidwhitney** [comment]
Actually, you know what, sod XML serialization, I've just hand rolled a cookie serializer for .NET40 - basically query string encoding. Seems to be fine. I'll wrap up test coverage around these bits tomorrow and push some updated packages with .NET40 support.

**Comment by rschiefer** [comment]
Sounds great, thanks!

Sent from my Windows Phone
________________________________

**Comment by davidwhitney** [comment]
Up on Nuget now. Have fun, let me know if anything doesn't work as you'd expect :)

**Comment by rschiefer** [comment]
Will do, thanks!

Sent from my Windows Phone
________________________________
